In [12]:
import os
import pandas as pd

In [2]:
df = pd.DataFrame({})

In [3]:
l = []
for file in os.listdir("./Data"):
    l.append(file)

for i in l[:5]:
    df = pd.concat([df,pd.read_parquet(f"./Data/{i}")],axis=0)

df.shape

(19699584, 20)

In [4]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2025-09-01 00:19:20,2025-09-01 00:45:17,1.0,9.92,1.0,N,138,114,1,42.90,6.0,0.5,10.73,0.0,1.0,66.13,2.5,1.75,0.75
1,2,2025-09-01 00:15:20,2025-09-01 00:26:08,2.0,6.82,1.0,N,93,157,1,26.80,1.0,0.5,5.86,0.0,1.0,35.16,0.0,0.00,0.00
2,2,2025-09-01 00:06:07,2025-09-01 00:22:23,1.0,3.95,1.0,N,68,13,1,19.80,1.0,0.5,5.11,0.0,1.0,30.66,2.5,0.00,0.75
3,2,2025-09-01 00:49:47,2025-09-01 01:04:49,1.0,3.14,1.0,N,234,87,1,17.70,1.0,0.5,3.52,0.0,1.0,26.97,2.5,0.00,0.75
4,2,2025-09-01 00:05:00,2025-09-01 00:15:32,6.0,2.81,1.0,N,230,151,1,14.90,1.0,0.5,4.13,0.0,1.0,24.78,2.5,0.00,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3970548,2,2025-04-30 23:37:25,2025-05-01 00:06:12,NaN,8.77,NaN,None,48,243,0,-4.75,0.0,0.5,0.00,0.0,1.0,5.07,NaN,NaN,0.75
3970549,2,2025-04-30 23:53:37,2025-05-01 00:12:34,NaN,3.20,NaN,None,234,142,0,21.00,0.0,0.5,0.00,0.0,1.0,25.75,NaN,NaN,0.75
3970550,2,2025-04-30 23:31:55,2025-04-30 23:46:09,NaN,2.49,NaN,None,68,45,0,-4.75,0.0,0.5,0.00,0.0,1.0,3.81,NaN,NaN,0.75
3970551,2,2025-04-30 23:27:36,2025-04-30 23:49:01,NaN,3.23,NaN,None,186,141,0,20.41,0.0,0.5,0.00,0.0,1.0,25.16,NaN,NaN,0.75
3970552,2,2025-04-30 23:05:47,2025-04-30 23:16:32,NaN,1.82,NaN,None,158,164,0,-4.75,0.0,0.5,0.00,0.0,1.0,4.99,NaN,NaN,0.75

In [5]:
df = df[["tpep_pickup_datetime","tpep_dropoff_datetime","passenger_count","trip_distance","PULocationID","DOLocationID"]]

In [6]:
df

,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,PULocationID,DOLocationID
0,2025-09-01 00:19:20,2025-09-01 00:45:17,1.0,9.92,138,114
1,2025-09-01 00:15:20,2025-09-01 00:26:08,2.0,6.82,93,157
2,2025-09-01 00:06:07,2025-09-01 00:22:23,1.0,3.95,68,13
3,2025-09-01 00:49:47,2025-09-01 01:04:49,1.0,3.14,234,87
4,2025-09-01 00:05:00,2025-09-01 00:15:32,6.0,2.81,230,151
...,...,...,...,...,...,...
3970548,2025-04-30 23:37:25,2025-05-01 00:06:12,NaN,8.77,48,243
3970549,2025-04-30 23:53:37,2025-05-01 00:12:34,NaN,3.20,234,142
3970550,2025-04-30 23:31:55,2025-04-30 23:46:09,NaN,2.49,68,45
3970551,2025-04-30 23:27:36,2025-04-30 23:49:01,NaN,3.23,186,141
3970552,2025-04-30 23:05:47,2025-04-30 23:16:32,NaN,1.82,158,164

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19699584 entries, 0 to 3970552
Data columns (total 6 columns):
 #   Column                 Dtype
---  ------                 -----
 0   tpep_pickup_datetime   datetime64[us]
 1   tpep_dropoff_datetime  datetime64[us]
 2   passenger_count        float64
 3   trip_distance          float64
 4   PULocationID           int32
 5   DOLocationID           int32
dtypes: datetime64[us](2), float64(2), int32(2)
memory usage: 901.8 MB

In [ ]:
df["duration"] = df["tpep_dropoff_datetime"] - df["tpep_pickup_datetime"] 
df = df.drop(columns=['tpep_pickup_datetime','tpep_dropoff_datetime'])
df['duration'] = df['duration'].dt.total_seconds()